### ISSUE TITLE
66h + xbegin shouldn't truncate the target address

### ISSUE THREAD

**Issue by 0xd4d** [intelxed/xed#214]
`xbegin` is a little bit different than the other rel branch instructions.

SDM: ` (Use of the 16-bit operand size does not cause this address to be truncated to 16 bits, unlike a near jump to a relative offset.)`

```
./xed -64 -d 66 C7 F8 5AA5
```

Actual:

```
xbegin 0xa55f
```

Expected:

```
xbegin 0xffffffffffffa55f
```

**Comment by markcharney** [comment]
I fixed this internally. I don't really like the fix since I had to basically say "If xbegin, don't truncate the address". But maybe it'll motivate me to enable a more generic solution one day.  I have a massive backlog of patches to release externally, but this is fixed. I'm assuming this is not a show stopper for anyone...

**Comment by markcharney** [comment]
fixed in spring.
