### ISSUE TITLE
Compiling on aarch-64 fails

### ISSUE THREAD

**Issue by 834352982** [intelxed/xed#239]
Hi, i am trying to compile xed on arm, is there a plan for this?

**Comment by markcharney** [comment]
Interesting question. Currently it is not supported. First request that I  have received for that. If I can located an arm development system, then I can take a look. The binary file readers in the  examples won't  work  cross  platform due to  missing system  headers. Everything  else will, I  think.  I'd  have  to  replace the inline asm used for reading  the x86 time stamp   counter (RDTSC) with   something, or  just omit it.  That's just  for  regression timing. It is probably  just  a  matter of defining a new host type in mbuild  and some build configuration flags.

**Comment by 834352982** [comment]
Thanks for the response.

**Comment by markcharney** [comment]
I found an aarch64 system (on the other side of the world -- which is kinda cool) and got libxed to compile.  I  have not tried the examples  yet. To compile libxed, mbuild required  a  2  line patch  (below). I will incorporate   hat into  my  next external push to github. But if you want to try it, here you go:



```
:~/mbuild> git diff
diff --git a/mbuild/env.py b/mbuild/env.py
index 993ab46..b4518fa 100755
--- a/mbuild/env.py
+++ b/mbuild/env.py
@@ -1228,6 +1228,8 @@ class env_t(object):
             return 'x86-64'
         elif name[0:3] == 'x86':
             return 'ia32'
+        elif name == 'aarch64':
+            return 'aarch64'
         else:
             die("Unknown cpu " + name)

```

**Comment by 834352982** [comment]
Thank you very much. That's how I solved it.

**Comment by markcharney** [comment]
Another  small  fix  to   the  xed sources gets  the examples to compile too.  I even decoded an instruction. Pretty   cool  :-)

```
/tmp/mjcharne/xed> git  diff
diff --git a/include/public/xed/xed-get-time.h b/include/public/xed/xed-get-time.h
index 07eccf97..e9a74cb4 100644
--- a/include/public/xed/xed-get-time.h
+++ b/include/public/xed/xed-get-time.h
@@ -36,7 +36,9 @@ END_LEGAL */
 #         pragma intrinsic(__rdtsc)
 #      endif
 #      if defined(__GNUC__)
-#         include <x86intrin.h>
+#         if defined(__i386__) || defined(i386) || defined(i686) || defined(__x86_64__)
+#            include <x86intrin.h>
+#         endif
 #      endif
 #   endif
```
