### ISSUE TITLE
Support for L10M/K10M/KNC instructions via XED_CHIP_ALL

### ISSUE THREAD

**Issue by woodruffw** [intelxed/xed#255]
Similar to #250: `c57baef5` decodes to `SPFLT ebp`, but decoding with `XED_CHIP_ALL` produces an error instead.

**Comment by markcharney** [comment]
thx. KNC support in XED on life support. But this  seems like it could be related to #250.

**Comment by markcharney** [comment]
I  had  to  omit some  instr to  get KNC  to build again (and I'll push out a patch  for  that).  But when  I did, your example worked for me.  Can  you supply more information please?


```
% obj-knc/wkit/bin/xed -chip-check ALL -64  -d c5 7b ae f5
Setting chip to ALL
C57BAEF5
ICLASS:     SPFLT
CATEGORY:   KNCSCALAR
EXTENSION:  KNC
IFORM:      SPFLT_GPR32d
ISA_SET:    KNCV
ATTRIBUTES: 
SHORT:      spflt ebp
```

**Comment by tremalrik** [comment]
Given the title of this issue, a (rather theoretical) issue with supporting L1OM under something like XED_CHIP_ALL is that there exist some opcode collisions betwen L1OM and AVX-512. E.g. the 6-byte sequence `62 81 CF C1 11 C0` decodes to two instructions under L1OM (`bsri r15,r9` followed by `rcl dword ptr [rcx],0xc0`) but only one instruction under AVX-512 (`vmovsd xmm24{k1}{z}, xmm22, xmm16`). K1OM/KNC does not appear to have any such conflicts with AVX-512, though.

This is probably a rather moot issue, though, since XED has not supported L1OM in a very long time (if ever), and has officially dropped K1OM/KNC support from "External Release v2022.08.11" onwards.
