### ISSUE TITLE
xed_enc_vfmadd231ps_y_y_y_256 encodes as xed_enc_vfmadd231pd_y_y_y_256

### ISSUE THREAD

**Issue by eric-lemurian** [intelxed/xed#309]
when disassembling generated code using xed_enc_vfmadd231ps_y_y_y_256 in gdb, shows vfmadd231pd,
and the results are consistent with a double operation.

if I cut and paste the body of xed_enc_vfmadd231ps_y_y_y_256 and
set r->s.rexw to zero before calling emit_vex_cr4, it both generates the correct opcode from gdb's perspective
and produces the expected result

found a similar issue with xed_enc_vpbroadcastd_y_r32_256_e, it gets encoded as vpbroadcastq

**Comment by kkhalail** [comment]
Hi Eric,
I just tested it out and it doesn't seem to be a problem. Did you make sure that the enc2 structure was properly initialized?
Because rexw isn't explicitly set in xed_enc_vfmadd231ps_y_y_y_256 and neither in any of the sub-enc functions (e.g. enc_modrm_rm_ymm).
Feel free to provide more information.

**Comment by kkhalail** [comment]
Couldn't duplicate the issue
