### ISSUE TITLE
Failure to decode c5 92 12 00

### ISSUE THREAD

**Issue by pgoodman** [intelxed/xed#31]
This does not decode:
```c5 92 12 00             vmovsldup xmm0,XMMWORD PTR [rax]```

Test setup uses `examples/xed-dec-print.c`, but with lines 38-45 changed to:

```C
    // example instructions
    xed_uint_t   bytes = 4;
    xed_uint8_t  itext[XED_MAX_INSTRUCTION_BYTES] = { 0xc5, 0x92, 0x12, 0x00 };

    xed_tables_init();
    
    mmode=XED_MACHINE_MODE_LONG_64;
    stack_addr_width=XED_ADDRESS_WIDTH_64b;
```

**Comment by markcharney** [comment]
Hi Peter!
This instr, since it only has 2 operands, requires VEX.vvvv to be all 1s. So your VEX payload needs to be RvvvvLpp = 1_1111_0_10 = FA

obj/examples/xed -d c5 fa 12 00
C5FA1200
ICLASS: VMOVSLDUP   CATEGORY: DATAXFER   EXTENSION: AVX  IFORM: VMOVSLDUP_XMMdq_MEMdq   ISA_SET: AVX
SHORT: vmovsldup xmm0, xmmword ptr [eax]

Dare, I ask what generated the problematic byte sequence? If it was XED, let me know!

**Comment by pgoodman** [comment]
Mark,

Thanks for the quick reply! It came up when looking at bytes of a jump table embedded within the code section in a binary. So, the bytes themselves aren't part of actual code, but the producer of some input to my Remill project thought those bytes were code, and then Remill crashed when trying to decode those bytes. So, XED is not at fault!

So, conclusion is that XED is right, and IDA Pro and others are wrong?

**Comment by markcharney** [comment]
If you believe it is really supposed to be code, and not data, whatever made that instr, did it wrong. That instruction requires VEX.vvvv = 0b1111.  If possible, I'd suggest reporting a bug to that software. Thanks!

Regards,
Mark

**Comment by markcharney** [comment]
I'll close this. If you have any other questions, don't hesitate.
