### ISSUE TITLE
Invalid conversion mode for Sf32-class MVEX instructions

### ISSUE THREAD

**Issue by flobernd** [intelxed/xed#51]
Sorry for opening another issue, but I might have found a bug regarding MVEX conversion functionality. The following instruction should be invalid:
```
62 f1 78 59 59 00 | vmulps zmm0, k1, zmm0, xmmword ptr [rax]{sint8}
```
Table of valid MVEX.SSS values:
```
S2S1S0 | Function                  | Usage
-----------------------------------------------------
000    | no conversion             | [rax]
001    | broadcast 1 element (x16) | [rax] {1to16}
010    | broadcast 4 elements (x4) | [rax] {4to16}
011    | float16 to float32        | [rax] {float16}
100    | uint8 to float32          | [rax] {uint8}
101    | reserved                  | N/A
110    | uint16 to float32         | [rax] {uint16}
111    | sint16 to float32         | [rax] {sint16}
```
I did not test all of the other classes, but at least for Si32 (e.g. vpaddsetsd) XED correctly detects `MVEX.SSS = 011` as invalid.

**Comment by markcharney** [comment]
MVEX.. might I ask what it is you are doing? I was hoping not to invest much time in that older stuff as that ISA essentially got "upgraded" when AVX512 came out.   It has been many years since I looked at this part of the ISA, but I think VMULPS uses table the Sf32 (subscript f32) table on page 403 of the  KNC programmers reference: 
https://software.intel.com/sites/default/files/forum/278102/327364001en.pdf

You are referring to table 2.4 (page 30) which is something else.

**Comment by flobernd** [comment]
Thanks for your reply! I think you are right.

I'm currently comparing the output of our own disassembler library against other disassemblers with the intention to find some bugs on my side (with the side-effect to sometimes stumble across bugs in the libraries I'm comparing against).
