### ISSUE TITLE
MOV_MEMw_SEG should be SCALABLE?

### ISSUE THREAD

**Issue by pgoodman** [intelxed/xed#66]
The bytes `48 8c 20` decode to a `MOV_MEMw_SEG`, operating on a 64-bit memory operand. It seems like this should really be named as a `MOV_MEMv_SEG` and marked with the `SCALABLE` attribute.

**Comment by markcharney** [comment]
I'll have to research this one.  AMD docs say the memop dest is always 16b.

**Comment by markcharney** [comment]
Hi Peter, I poked around. This instr always writes a 16b memop. I have not written a program to verify that though.  Intel SDM is a little vague on 32b EOSZ.  AMD docs imply that one can write a 16/32/64 register or a 16b memop.  If you have information to the contrary, please share it. Thanks!

**Comment by pgoodman** [comment]
I made two programs to test it and it seems that the AMD docs are correct! I guess this line in the Intel manual is incorrect:

![image](https://user-images.githubusercontent.com/43664/29831342-cf372060-8cb2-11e7-8565-6ecb227634a5.png)

My first program modified a `uint64_t` initialized with `~0`. That showed that only the low two bytes got overwritten with the segment selector. The second test operated on an `mmap`ed address, pointing the instruction at the last two bytes of the memory map. That did not produce a fault, and so I think it's safe so say that the memory operand is 16 bits.

I think this now becomes a bug report where `xed_decoded_inst_get_operand_width` on this instruction produces 64.

**Comment by markcharney** [comment]
Hi Peter,
I cannot reproduce that bug report you linked to.   I get a "word" reference (below). Can you give me a reproducer for the error you saw? 

As far as the effective operand size (EOSZ)... The EOSZ is essentially an intermediate input to decoding (derived in the conventional way from the mode, REX.W and 66 prefixes). Some instructions pay attention to it and some do not. This one does not.  In some cases I've had to tweak/override the normal EOSZ so that decoding works properly (like for things that default to 64b decoding).  This instr does not require that.


```
% obj/examples/xed -64 -d 488c20
488C20
ICLASS: MOV   CATEGORY: DATAXFER   EXTENSION: BASE  IFORM: MOV_MEMw_SEG   ISA_SET: I86
SHORT: mov word ptr [rax], fs
```

**Comment by pgoodman** [comment]
Ah I see. I was using a function that technically only applies to `SCALABLE` instructions: https://github.com/trailofbits/remill/blob/0e82521e4693333d352b0270b95f380d677b8a3e/remill/Arch/X86/Arch.cpp#L382

**Comment by markcharney** [comment]
ok. i requested a clarification to the intel sdm. anything else or is this on close-able?

**Comment by pgoodman** [comment]
Thanks! Close-able :-)
