### ISSUE TITLE
States conflict between not64 and DF64() at PUSH/POP-FD inst

### ISSUE THREAD

**Issue by lyrachord** [intelxed/xed#90]
Hi,
```
PATTERN   : 0x9C DF64() EOSZ=2 not64
PATTERN   : 0x9D DF64() EOSZ=2 not64
```
Seems DF64() should be removed

**Comment by markcharney** [comment]
If you look at what you show in isolation, you are correct, but there is something else going on here. Let me try to explain. 

background: 0x9C (and 0x9D) behave differently depending on the effective operand size (EOSZ) and the mode. They default to 64b EOSZ in 64b mode.  

The 2nd major version of XED (xed2) used a graph partitioning and traversal to decode. The current version (xed3) does not use the graph traversal for decode. But the graph partitioning step is still done at build time because it is a very helpful way of finding opcode allocation conflicts when I am allocating opcodes for new instructions for future designs.  One of the limitations of that graph partitioning algorithm is that the nonterminals (like DF64) have to "line up", modulo some limited juggling of certain constraints that XED is capable of doing.   So in order to do the graph partitioning of the 9C and 9D opcodes, I need to have the same nonterminals for the EOSZ=1,2,3 cases. And that results in what you see for the 3 EOSZ cases (16,32,64b):

0x9C DF64() EOSZ=1
0x9C DF64() EOSZ=2 not64
0x9C DF64() EOSZ=3 mode64

(The mode64 on the 3rd one is not required since we cannot get EOSZ=3 from DF64() otherwise).
If I remove the DF64() from the 32b (EOSZ=2) case, then the graph partitioner would get confused.

I could express it differently. Something like:

16b: 0x9C mode64 66_prefix norexw_prefix
16b: 0x9C mode32 66_prefix 
16b: 0x9C mode16 no66_prefix
32b: 0x9C mode16 66_prefix
32b: 0x9C mode32 no66_prefix
64b: 0x9C mode64 no66_prefix 
64b: 0x9C mode64 66_prefix rexw_prefix

Possibly that is a little more obvious, but more work for everything that uses DF64-semantics.
And then I'd have to do something to get df64 set so that it re-encodes properly.

Anyway, I hope this makes sense. Hopefully I understood your question and did not go off on a huge tangent. :-)
